processes:
  worker:
    system:
      watch_queues: 
        - *
      include_retrying: false
      include_scheduled: true
    scale:
      mode: binary
      max_workers: 1

  other_worker:
    system:
      watch_queues:
        - default
        - high
        - low
      include_retrying: false
      include_scheduled: true
    scale:
      mode: linear
      max_workers: 1
      worker_capacity: 25
      min_factor: 0